FROM python:3.8.6

WORKDIR /app

COPY requirements-actions.txt ./

USER root

RUN pip install --no-cache-dir -r requirements-actions.txt

COPY actions actions/

USER 1001

EXPOSE $PORT

CMD ["sh", "-c", "python -m rasa_sdk --actions actions -p $PORT"]