FROM python:3.8.6

COPY ./actions /app/actions
COPY ./requirements-actions.txt /app/requirements-actions.txt

WORKDIR /app

USER root

RUN pip install --no-cache-dir -r requirements-actions.txt

USER 1001

EXPOSE $PORT

CMD ["sh", "-c", "python -m rasa_sdk --actions actions -p $PORT"]